=== avouacr/job-offers-recommender/CV_builder_draft/cv_generator/cv.schema.json
{
	"$schema": "http://json-schema.org/schema#",
	"type": "object",
	"properties": {
		"lang": {
			"type": "string",
			"enum": [
				"es-ES",
				"en-US",
				"fr-FR"
			]
		},
		"last_update": {
			"type": "string",
			"pattern": "^\\d{4}-([0]\\d|1[0-2])-([0-2]\\d|3[01])$"
		},
		"basic": {
			"type": "object",
			"properties": {
				"name": {
					"type": "string"
				},
				"surnames": {
					"type": "string"
				},
				"profession": {
					"type": "string"
				},
				"birthday": {
					"type": "string",
					"pattern": "^\\d{4}-([0]\\d|1[0-2])-([0-2]\\d|3[01])$"
				},
				"birthplace": {
					"type": "string"
				},
				"residence": {
					"type": "string"
				},
				"marital_status": {
					"type": "string"
				},
				"biography": {
					"type": "string"
				},
				"hobbies": {
					"type": "string"
				}
			}
		},
		"contact": {
			"type": "object",
			"properties": {
				"email": {
					"type": "string"
				},
				"phone": {
					"type": "string"
				},
				"website": {
					"type": "object",
					"properties": {
						"anchor": {
							"type": "string"
						},
						"href": {
							"type": "string"
						}
					}
				},
				"twitter": {
					"type": "object",
					"properties": {
						"anchor": {
							"type": "string"
						},
						"href": {
							"type": "string"
						}
					}
				},
				"linkedin": {
					"type": "object",
					"properties": {
						"anchor": {
							"type": "string"
						},
						"href": {
							"type": "string"
						}
					}
				},
				"github": {
					"type": "object",
					"properties": {
						"anchor": {
							"type": "string"
						},
						"href": {
							"type": "string"
						}
					}
				},
				"scholar": {
					"type": "object",
					"properties": {
						"anchor": {
							"type": "string"
						},
						"href": {
							"type": "string"
						}
					}
				}
			}
		},
		"experience": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"institution": {
						"type": "string"
					},
					"position": {
						"type": "string"
					},
					"date_start": {
						"type": "string",
						"pattern": "^\\d{4}-([0]\\d|1[0-2])-([0-2]\\d|3[01])$"
					},
					"date_end": {
						"type": "string",
						"pattern": "^\\d{4}-([0]\\d|1[0-2])-([0-2]\\d|3[01])$"
					},
					"description": {
						"type": "string",
						"minLength": 1
					}
				}
			},
			"uniqueItems": true
		},
		"education": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"institution": {
						"type": "string"
					},
					"degree": {
						"type": "string"
					},
					"major": {
						"type": "string"
					},
					"date_start": {
						"type": "string",
						"pattern": "^\\d{4}-([0]\\d|1[0-2])-([0-2]\\d|3[01])$"
					},
					"date_end": {
						"type": "string",
						"pattern": "^\\d{4}-([0]\\d|1[0-2])-([0-2]\\d|3[01])$"
					},
					"description": {
						"type": "string"
					},
					"gpa": {
						"type": "number",
						"minimum": 0
					},
					"gpa_max": {
						"type": "number",
						"minimum": 0
					},
					"performance": {
						"type": "number",
						"minimum": 0,
						"maximum": 100
					},
					"promotion_order": {
						"type": "string"
					}
				}
			},
			"uniqueItems": true
		},
		"awards": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"institution": {
						"type": "string"
					},
					"name": {
						"type": "string"
					},
					"date": {
						"type": "string",
						"pattern": "^\\d{4}-([0]\\d|1[0-2])-([0-2]\\d|3[01])$"
					},
					"description": {
						"type": "string"
					},
					"diploma": {
						"type": "object",
						"properties": {
							"anchor": {
								"type": "string"
							},
							"href": {
								"type": "string"
							}
						}
					}
				}
			}
		},
		"publications": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"title": {
						"type": "string"
					},
					"abstract": {
						"type": "string"
					},
					"authors": {
						"type": "string"
					},
					"date": {
						"type": "string",
						"pattern": "^\\d{4}-([0]\\d|1[0-2])-([0-2]\\d|3[01])$"
					},
					"manuscript_link": {
						"type": "object",
						"properties": {
							"anchor": {
								"type": "string"
							},
							"href": {
								"type": "string"
							}
						}
					},
					"code_link": {
						"type": "object",
						"properties": {
							"anchor": {
								"type": "string"
							},
							"href": {
								"type": "string"
							}
						}
					}
				}
			},
			"unique": true
		},
		"languages": {
			"type": "array",
			"items": {
				"type": "object",
				"parameters": {
					"name": {
						"type": "string"
					},
					"level": {
						"type": "string",
						"enum": [
							"A1",
							"A2",
							"B1",
							"B2",
							"C1",
							"C2",
							"Native"
						]
					},
					"diploma": {
						"type": "object",
						"properties": {
							"anchor": {
								"type": "string"
							},
							"href": {
								"type": "string"
							}
						}
					}
				}
			},
			"unique": true
		},
		"courses": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"institution": {
						"type": "string"
					},
					"name": {
						"type": "string"
					},
					"date": {
						"type": "string",
						"pattern": "^\\d{4}-([0]\\d|1[0-2])-([0-2]\\d|3[01])$"
					},
					"diploma": {
						"type": "object",
						"properties": {
							"anchor": {
								"type": "string"
							},
							"href": {
								"type": "string"
							}
						}
					}
				}
			},
			"unique": true
		},
		"projects": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"name": {
						"type": "string"
					},
					"description": {
						"type": "string"
					},
					"link": {
						"type": "object",
						"properties": {
							"anchor": {
								"type": "string"
							},
							"href": {
								"type": "string"
							}
						}
					}
				}
			}
		},
		"skills": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"name": {
						"type": "string"
					},
					"type": {
						"type": "string"
					},
					"category": {
						"type": "string"
					},
					"score": {
						"type": "number",
						"minimum": 0,
						"maximum": 100
					}
				}
			},
			"minItems": 0,
			"unique": true
		}
	}
}

=== avouacr/job-offers-recommender/CV_builder_draft/cv_generator/cv.example.en-us.json
{
  "lang": "en-US",
  "last_update": "2020-04-11",
  "basic": {
    "name": "David",
    "surnames": "Álvarez de la Torre",
    "profession": "Data Scientist | Telecommunication Engineer",
    "birthday": "1996-01-20",
    "birthplace": "Barcelona",
    "residence": "Zurich",
    "marital_status": "Single",
    "biography": "Passionate about technology and engineering. Junior researcher working on generative models, with two accepted peer-reviewed papers (one of them at ICLR). Currently doing my MSc. thesis working on video inpainting at the Computer Vision Laboratory of ETH Zürich.\nI studied my bachelor's and master's in Telecommunications Engineering at the Polytechnic University of Catalonia (UPC), ranked first for engineering studies in Spain and 51-100 worldwide in the field of Electrical Engineering (QS World Ranking 2020).\nI have had the pleasure to work hand-in-hand with the best researchers (of my field) in Spain. In 2019, I interned in both the VEU department of UPC and in Telefonica Research, one of the few industrial research laboratories of the country.\nWith experience releasing open-source projects. Passionate about sharing easy-to-use code and reproducible experiments. Also experienced in web development and Internet businesses.",
    "hobbies": "Gym, traveling, Netflix and to wait for delayed trains."
  },
  "contact": {
    "email": "davidalvarezdlt@gmail.com",
    "phone": "(+34) 666 77 88 99",
    "personal_website": {
      "anchor": "davidalvarezdlt.com",
      "href": "https://en.davidalvarezdlt.com/"
    },
    "twitter": {
      "anchor": "Twitter",
      "href": "https://twitter.com/DavidAlvarezDLT"
    },
    "linkedin": {
      "anchor": "LinkedIn",
      "href": "https://www.linkedin.com/in/davidalvarezdlt/"
    },
    "github": {
      "anchor": "GitHub",
      "href": "https://github.com/davidalvarezdlt"
    },
    "scholar": {
      "anchor": "Google Scholar",
      "href": "https://scholar.google.es/citations?user=WK4V8VUAAAAJ&hl=es"
    }
  },
  "experience": [
    {
      "institution": "Telefónica Research",
      "position": "Research Intern",
      "date_start": "2019-06-01",
      "date_end": "2019-11-30",
      "description": "Worked hand-in-hand with Dr. Joan Serrà on the detection of out-of-distribution using generative models. Implemented both the experiments and models (Glow and PixelCNN++) used in the paper \"Input Complexity and Out-of-distribution Detection with Likelihood-based Generative Models\", accepted at the International Conference on Learning Representations of 2020.\nI also worked on the creation of a tool to generate text-to-speech voice data sets from YouTube videos, published in my GitHub profile."
    },
    {
      "institution": "Polytechnic University of Catalonia",
      "position": "Research Fellow",
      "date_start": "2018-12-01",
      "date_end": "2019-05-31",
      "description": "Obtained a scholarship from the Spanish Government to intern in the department of my choice. I chose the VEU department, led by Dr. Antonio Bonafonte and focused on the development of voice technologies.\nWorked under the supervision of Dr. Santiago Pascual on text-to-speech systems, publishing the paper \"Problem-agnostic speech embeddings for multi-speaker text-to-speech with SampleRNN\", accepted as an oral at the 10th ISCA Speech Synthesis Workshop."
    }
  ],
  "education": [
    {
      "institution": "ETH Zürich",
      "degree": "Exchange Student",
      "major": "Computer Vision Lab",
      "date_start": "2020-02-01",
      "date_end": "2020-07-31",
      "description": "Working on video inpainting under the supervision of Sergi Caelles, Dr. Martin Danelljan, Prof. Xavier Giró-i-Nieto, and Prof. Luc Van Gool."
    },
    {
      "institution": "Polytechnic University of Catalonia",
      "degree": "MSc. Telecommunications Engineering",
      "major": "Multimedia Intensification",
      "date_start": "2018-09-01",
      "date_end": "2020-07-31",
      "description": "Official 2-year master's program (120 ECTS) leading to the title of Telecommunications Engineer, which grants the right to lead and sign Telecommunications projects in the Spanish territory.\nChose the intensification in multimedia systems, with coursework including subjects such as \"Computer Vision\", \"Machine Learning\" or \"Advanced Human Language Technologies\". I also took 15 elective ECTS credits of \"Introduction to Research\", obtaining the maximum qualification and honors.\nObtained the nomination of my university to complete the master writing my thesis at ETH Zürich, one of the most competed universities in the exchange program.",
      "gpa": 8.87,
      "gpa_max": 10.0,
      "performance": 100.0
    },
    {
      "institution": "Polytechnic University of Catalonia",
      "degree": "BSc. Telecommunications Technologies and Services Engineering",
      "major": "Audiovisual Specialization",
      "date_start": "2014-09-01",
      "date_end": "2018-07-31",
      "description": "Official 4-year bachelor’s program (240 ECTS) leading to the title of Technical Telecommunications Engineer, a regulated profession in the Spanish territory.\nChose the audiovisual specialization, with coursework including subjects such as “Audio and voice signal processing, “Image and video signal processing”, “Audiovisual coding”, “Acoustics and electroacoustic” or “Pattern recognition”.\nWrote my thesis titled “Real-time stock predictions with Deep Learning and news scrapping” under the supervision of Prof. José Adrián Rodríguez Fonollosa, obtaining a final qualification of 9.70 / 10.00.",
      "gpa": 7.72,
      "gpa_max": 10.0,
      "performance": 100.0,
      "promotion_order": "22 / 373"
    }
  ],
  "awards": [
    {
      "institution": "Ministry of Education, Culture and Sports",
      "name": "Collaboration Scholarship",
      "date": "2018-11-01",
      "description": "Scholarship of €2000 whose purpose is to initiate students in research tasks in the department of their choice. Awarded annually to nearly 2000 applicants with the best average mark in Spanish territory."
    },
    {
      "institution": "Polytechnic University of Catalonia",
      "name": "Bachelor's Excellence Letter",
      "date": "2018-11-26",
      "description": "Granted to those students who pass all subjects in the first attempt without failing any one of them. Yearly students with this recognition between 10-20%.",
      "diploma": {
        "anchor": "Recognition",
        "href": "https://davidalvarezdlt.cdn.prismic.io/davidalvarezdlt/661dd369-0264-40aa-9236-edbaeb32502b_sobre-mi-reconocimientos-excelencia.pdf"
      }
    },
    {
      "institution": "CARNET Barcelona",
      "name": "Hackathon Mobility 2018 - First Place of the SEAT Challenge",
      "date": "2018-03-11",
      "description": "The Hackathon consisted of combining the sensors of a robot with Amazon Alexa to create a smart driving assistant. Our solution included functionalities such as face detection, face recognition, facial gesture detection, event alerts and the inclusion of an innovative optimal refueling algorithm.",
      "diploma": {
        "anchor": "Prize",
        "href": "https://davidalvarezdlt.cdn.prismic.io/davidalvarezdlt%2F9c868325-3e7a-40a7-a961-6afaf25f67b3_sobre-mi-premios-hackmob2018.pdf"
      }
    }
  ],
  "publications": [
    {
      "title": "Input complexity and out-of-distribution detection with likelihood-based generative models",
      "abstract": "Likelihood-based generative models are a promising resource to detect out-of-distribution (OOD) inputs which could compromise the robustness or reliability of a machine learning system. However, likelihoods derived from such models have been shown to be problematic for detecting certain types of inputs that significantly differ from training data. In this paper, we pose that this problem is due to the excessive influence that input complexity has in generative models' likelihoods. We report a set of experiments supporting this hypothesis, and use an estimate of input complexity to derive an efficient and parameter-free OOD score, which can be seen as a likelihood-ratio, akin to Bayesian model comparison. We find such score to perform comparably to, or even better than, existing OOD detection approaches under a wide range of data sets, models, model sizes, and complexity estimates.",
      "authors": "Joan Serrà, David Álvarez, Vicenç Gómez, Olga Slizovskaia, José F Núñez and Jordi Luque",
      "date": "2020-04-20"
    },
    {
      "title": "Problem-agnostic speech embeddings for multi-speaker text-to-speech with SampleRNN",
